name: Build and deploy ASP apps to Azure Web App - helloworld-demo-123

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '/published/**'

  deploy-staging:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10127C0438E940C5AF72D809EC856C4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F74474E9BE7E48CEB9F2BD42A3E8DDA2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC1E64DDE47F4068B38D1FFC40735053 }}


      - name: Deploy to Azure Web App (Staging Slot)
        id: deploy-to-webapp-staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'helloworld-demo-123'
          slot-name: 'staging'
          package: .

  deploy-production:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-production.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10127C0438E940C5AF72D809EC856C4A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F74474E9BE7E48CEB9F2BD42A3E8DDA2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC1E64DDE47F4068B38D1FFC40735053 }}

      - name: Deploy to Azure Web App (Production Slot)
        id: deploy-to-webapp-production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'helloworld-demo-123'
          slot-name: 'Production'
          package: .
          
